### ISSUE TITLE
"npm run build" giving errors

### ISSUE THREAD

**Issue by dgurudot** [SuperPenguin/charting-library-flutter#1]
vmacair@vMacAir chart-project % pwd
/Users/vmacair/StudioProjects/charting-library-flutter/chart-project
vmacair@vMacAir chart-project % ls -ltr
total 1192
drwxr-xr-x    6 vmacair  staff     192 Jul 25 22:40 src
drwxr-xr-x    2 vmacair  staff      64 Jul 25 23:02 dist
drwxr-xr-x  539 vmacair  staff   17248 Jul 25 23:02 node_modules
-rw-r--r--    1 vmacair  staff  602183 Jul 25 23:02 package-lock.json
-rw-r--r--    1 vmacair  staff     482 Jul 25 23:02 package.json
vmacair@vMacAir chart-project % ls -ltr src/charting-library 
total 168
-rwxrwxrwx  1 vmacair  staff  12463 Jul 25 09:46 index.js
-rwxrwxrwx  1 vmacair  staff  67863 Jul 25 09:46 index.d.ts
vmacair@vMacAir chart-project % sudo npm run build          

> chart-project@1.0.0 build
> parcel build src/tvchart.html --public-url ./ --no-content-hash --no-source-maps

🚨  /Users/vmacair/StudioProjects/charting-library-flutter/chart-project/src/tvchart.ts:22:39: Cannot resolve dependency './charting-library/charting_library' at '/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/src/charting-library/charting_library'
    at Resolver.resolve (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at async Bundler.resolveAsset (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:433:18)
    at async Bundler.resolveDep (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 1)
    at async Bundler.loadAsset (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 1)
    at async Bundler.loadAsset (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Bundler.js:557:5)
vmacair@vMacAir chart-project %

**Comment by SuperPenguin** [comment]
Have you run `npm install` first?
Also make sure you open the js-project, not the root repo.

`/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/src/tvchart.ts:22:39: Cannot resolve dependency './charting-library/charting_library' at '/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/src/charting-library/charting_library'
at Resolver.resolve (/Users/vmacair/StudioProjects/charting-library-flutter/chart-project/node_modules/parcel-bundler/src/Resolver.js:71:17)`
looking at this, it seems the bundler can't find the lib, try renaming the esm version js file to
 `charting_library.js` and `charting_library.d.ts`
  or
   `index.js` and `index.d.ts`

**Comment by dgurudot** [comment]
I think instruction is missing that entire "charting_library" also has to be copied under src directory. Your response above gave me a clue along with error message and here is the latest output.

vmacair@vMacAir chart-project % npm run build

> chart-project@1.0.0 build
> parcel build src/tvchart.html --public-url ./ --no-content-hash --no-source-maps

✨  Built in 1.61s.

dist/tvchart.938d7a4b.js     15.61 KB    1.03s
dist/tvchart.html               353 B    466ms
dist/tvchart.a4df0666.css       119 B     44ms
vmacair@vMacAir chart-project % ls -ltr src
total 24
-rw-r--r--  1 vmacair  staff   172 Jul 25 22:35 tvchart.css
-rw-r--r--  1 vmacair  staff   388 Jul 25 22:35 tvchart.html
-rw-r--r--  1 vmacair  staff  4026 Jul 25 22:35 tvchart.ts
drwxr-xr-x  6 vmacair  staff   192 Jul 26 10:59 charting-library
vmacair@vMacAir chart-project %

**Comment by dgurudot** [comment]
![image](https://user-images.githubusercontent.com/58795306/127011832-e084e9f1-2cab-4bac-a652-32ff914290ea.png)

**Comment by SuperPenguin** [comment]
Yeah it seems the instruction a bit vague, also I just found out I don't need to rename files the bundler knows which to pick, you just need to copy these files, and ignore the other.

![Screen Shot 2021-07-26 at 22 58 12](https://user-images.githubusercontent.com/1574722/127020702-ed58a448-ebf4-4372-b445-a14bf8f2bf10.png)
