### ISSUE TITLE
Hello There ☺

### ISSUE THREAD

**Issue by NoobJj10101101** [SuperPenguin/charting-library-flutter#11]
I am trying to get a api key for tradingview and have read that i need a profile on the developer platform but cant find anything.. Do you have any advise ? 

Hope you are having a nice day 
kind regards Jonas Jessen

**Comment by SuperPenguin** [comment]
> I am trying to get a api key for tradingview and have read that i need a profile on the developer platform but cant find anything.. Do you have any advise ?
> 
> Hope you are having a nice day kind regards Jonas Jessen

https://www.tradingview.com/advanced-charts/
