### ISSUE TITLE
What should go inside public folder ?

### ISSUE THREAD

**Issue by dgurudot** [SuperPenguin/charting-library-flutter#2]
I have been trying to figure it out but couldn't get it working. Can you please expand and share details and possible example on what should go inside the public directory. I am using the instruction given below:

=========================================================================================
Create folder assets/tvchart/public, and paste all files charting-library needed (the one needed from library_path). This is assets folder should like right now.

=========================================================================================

**Comment by SuperPenguin** [comment]
Every files and folder in charting-library, except charting_library js, d.ts, and package.json

![image](https://user-images.githubusercontent.com/1574722/127032355-d1a9f54d-07be-4ebe-a4b6-bb56f4646e12.png)

**Comment by dgurudot** [comment]
You are awesome. Got it working and sharing the screenshot below for reference. The next step would be to connect the data source.

![image](https://user-images.githubusercontent.com/58795306/127033903-a5cc654f-845d-4c2b-9e43-30e7a703913b.png)

**Comment by dgurudot** [comment]
@SuperPenguin Did you have any data feed connected for the candlestick to show up on the chart as per screenshots shared in Readme for iOS and Android?

**Comment by SuperPenguin** [comment]
> @SuperPenguin Did you have any data feed connected for the candlestick to show up on the chart as per screenshots shared in Readme for iOS and Android?

No datafeed, it use random generated data.
https://github.com/SuperPenguin/charting-library-flutter/blob/64a4b234c4038018029e4112f0896d6f7efa65a1/flutter_app/lib/data/historical.dart#L162
