### ISSUE TITLE
Invalid Symbol Error after bars are loaded

### ISSUE THREAD

**Issue by imvab** [SuperPenguin/charting-library-flutter#4]
Hi 
After building and running the app I am not able to see the random historical bars and getting this symbol not found error.
I made this change since the arguments have changed. 

Please see if you are able to see the bars on the app.

<img width="759" alt="Screen Shot 2021-08-10 at 12 15 10 PM" src="https://user-images.githubusercontent.com/37765346/128820688-933261f6-3f82-4dc9-8c63-b5e45889ddda.png">

![simulator_screenshot_C2E853AC-553E-4D95-86CC-4B930B69AD6B](https://user-images.githubusercontent.com/37765346/128820889-3ff5fc00-f4b2-4fa9-9be5-ceb5e748b1a9.png)

**Comment by SuperPenguin** [comment]
It seems new version has some breaking API changes.
`getBars(symbolInfo: LibrarySymbolInfo, resolution: ResolutionString, periodParams: PeriodParams, onResult: HistoryCallback, onError: ErrorCallback): void;`

**Comment by SuperPenguin** [comment]
Fixed on c630f99d4b6ecd984d9f85167da352448eb77ea0
